version: '3.7'
services:
  awrtc_signaling:
    image: awrtc_signaling
    ports:
      - "80:80"
      - "443:443"
      - "12776:80"
      - "12777:443"
    logging:
        driver: "json-file"
        options:
            max-size: "100m"
            max-file: "10"
    volumes:
      - ./data/awrtc_signaling/config.json:/awrtc_signaling/config.json
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/awrtc_signaling/public:/awrtc_signaling/public
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/awrtc_signaling/public:/var/www/certbot